import { 
    Timer, Circle, Frown, Smile, Star, Send, Leaf, Rocket, RefreshCw, 
    Brain, ClipboardList, FileText, BarChart2, Target, AlertTriangle, 
    Ticket, MessageCircle, Calendar, Users, User, CheckCircle, Package, 
    Lock, Key, Wrench, DollarSign, CreditCard, Bot, Shield, XCircle, 
    Bell, Plug, Zap, Truck, Gift, Hand, ArrowDown, HelpCircle, Heart, 
    Mail, Radio, Search
} from 'lucide-react';

export const Icons = {
    Timer,
    Circle,
    Frown,
    Smile,
    Star,
    Send,
    Leaf,
    Rocket,
    RefreshCw,
    Brain,
    ClipboardList,
    FileText,
    BarChart2,
    Target,
    AlertTriangle,
    Ticket,
    MessageCircle,
    Calendar,
    Users,
    User,
    CheckCircle,
    Package,
    Lock,
    Key,
    Wrench,
    DollarSign,
    CreditCard,
    Bot,
    Shield,
    XCircle,
    Bell,
    Plug,
    Zap,
    Truck,
    Gift,
    Hand,
    ArrowDown,
    HelpCircle,
    Heart,
    Mail,
    Radio,
    Search
};
